def main():
    from bs4 import BeautifulSoup
    import os

    all_years_url = [
        "https://abesit.in/library/question-paper-bank/?dir=4405",
        "https://abesit.in/library/question-paper-bank/?dir=4406",
        "https://abesit.in/library/question-paper-bank/?dir=4407",
        "https://abesit.in/library/question-paper-bank/?dir=5020",
    ]

    for year_url in all_years_url:
        file_name_of_file_to_store_links = (
            "question_paper_bank/links/" + year_url.split("=")[1] + ".txt"
        )

        if os.path.exists(file_name_of_file_to_store_links):
            print("File already exists")
            continue

        if not os.path.exists(os.path.dirname(file_name_of_file_to_store_links)):
            os.makedirs(os.path.dirname(file_name_of_file_to_store_links))

        # r = requests.get(year_url)
        """<head><title>Not Acceptable!</title></head><body><h1>Not Acceptable!</h1><p>An appropriate representation of the requested resource could not be found on this server. This error was generated by Mod_Security.</p></body>"""
        # I think this is because of the mod_security in the server which is blocking the request from python script and hence the request is not getting through and hence the err

        # So I am using the requests_html library which is a wrapper around requests and beautifulsoup

        from requests_html import HTMLSession

        session = HTMLSession()

        r = session.get(year_url)

        soup = BeautifulSoup(r.html.html, "html.parser")

        print(soup)

        all_links = soup.find_all("a")

        print("Found " + str(len(all_links)) + " links")

        for link in all_links:
            if link.get("href").endswith(".pdf"):
                print(link.get("href"))
                # webbrowser.open(link.get('href'))

                with open(file_name_of_file_to_store_links, "a") as myfile:
                    myfile.write(link.get("href") + "\n")
